import {
	startStopContinue,
	timelineChronology,
	punlicToDoList,
	proudAndPity,
	leftRight,
	perfection,
	preElectionManifesto,
	fourWhos,
	repeatAndAvoid,
	satisfactionWithMeetings,
	newOldBlue,
	tweetMySprint,
	likeWishСould,
	averageHospitalTemperature,
	magicGin,
	inspectorGadget
} from './data/list';

const allScanariousForRetrogen = [
	startStopContinue,
  timelineChronology,
	punlicToDoList,
  proudAndPity,
	leftRight,
	perfection,
	preElectionManifesto,
	fourWhos,
	repeatAndAvoid,
	satisfactionWithMeetings,
	newOldBlue,
	tweetMySprint,
	likeWishСould,
	averageHospitalTemperature,
  magicGin,
  inspectorGadget
];

export {allScanariousForRetrogen, 	startStopContinue,
  timelineChronology,
	punlicToDoList,
  proudAndPity,
	leftRight,
	perfection,
	preElectionManifesto,
	fourWhos,
	repeatAndAvoid,
	satisfactionWithMeetings,
	newOldBlue,
	tweetMySprint,
	likeWishСould,
	averageHospitalTemperature,
  magicGin,
  inspectorGadget
 };
